version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=mydatabase
    ports:
      - 32768:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
