version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  app:
    build:
      context: ./app
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - mynetwork

  ai:
    build:
      context: ./ai
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
