version: '3'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
   

#   app:
#     build:
#       context: ./app
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     depends_on:
#       - db
#     networks:
#       - mynetwork

#   ai:
#     build:
#       context: ./ai
#       dockerfile: Dockerfile
#     depends_on:
#       - db
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
